# Use an official lightweight Python image
FROM python:3.8-slim

# Set the working directory in the Docker container
WORKDIR /app

# Copy the local directory contents to the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Run the application command
CMD ["gunicorn", "app:app", "--bind", "0.0.0.0:80"]
